version: "3.7"
services:
  web:
    container_name: cashback-admin-client
    volumes:
      - ".:/var/www/cashback-admin-client"
    stdin_open: true
    tty: true
    build:
      context: "."
      dockerfile: "./.docker/web.Dockerfile"
    ports:
      - "3001:3001"
